import ctypes
lib = ctypes.CDLL('./libmergeability.so')

# An object for working with the C/C++ library
class PMI(object):
	def __init__(self):
		self.obj = lib.PMI_init()

		# Configure ctypes to work with library functions
		lib.PMI_setClauses.restype = None
		lib.PMI_calculateMergeability.restype = None
		lib.PMI_calculate.restype = None
		lib.PMI_getMergeability.restype = ctypes.c_int
		lib.PMI_getMergeabilityScoreNorm1.restype = ctypes.c_double
		lib.PMI_getMergeabilityScoreNorm2.restype = ctypes.c_double
		lib.PMI_getPreResolutionClauseWidth.restype = ctypes.c_double
		lib.PMI_getPostResolutionClauseWidth.restype = ctypes.c_double

	def setClauses(self, clauses):
		arr = (ctypes.c_longlong * len(clauses))(*clauses)
		lib.PMI_setClauses.argtypes = [ ctypes.c_void_p, ctypes.c_longlong * len(clauses), ctypes.c_longlong ]
		lib.PMI_setClauses(self.obj, arr, len(clauses))

	def calculate(self, varSet, clauseFilterMode = 0):
		arr = (ctypes.c_longlong * len(varSet))(*varSet)
		lib.PMI_calculate.argtypes = [ ctypes.c_void_p, ctypes.c_longlong * len(varSet), ctypes.c_int ]
		lib.PMI_calculate(self.obj, arr, clauseFilterMode)

	def calculateMergeability(self, varSet):
		# This function is deprecated! Use calculate() instead
		self.calculateMergeability(varSet)

	def getMergeability(self):
		lib.PMI_getMergeability.argtypes = [ ctypes.c_void_p ]
		return lib.PMI_getMergeability(self.obj)

	# Normalize mergeability score by total number of resolvable pairs
	def getMergeabilityScoreNorm1(self):
		lib.PMI_getMergeabilityScoreNorm1.argtypes = [ ctypes.c_void_p ]
		return lib.PMI_getMergeabilityScoreNorm1(self.obj)

	# Normalize mergeability score by m^2
	def getMergeabilityScoreNorm2(self):
		lib.PMI_getMergeabilityScoreNorm2.argtypes = [ ctypes.c_void_p ]
		return lib.PMI_getMergeabilityScoreNorm2(self.obj)

	# Get the average clause width before resolution
	def getPreResolutionClauseWidth(self):
		lib.PMI_getPreResolutionClauseWidth.argtypes = [ ctypes.c_void_p ]
		return lib.PMI_getPreResolutionClauseWidth(self.obj)

	# Get the average clause width of clauses generated by the first step of resolution
	def getPostResolutionClauseWidth(self):
		lib.PMI_getPostResolutionClauseWidth.argtypes = [ ctypes.c_void_p ]
		return lib.PMI_getPostResolutionClauseWidth(self.obj)
